spring:
  application:
    name: gateway-web
  #Redis配置
  redis:
    host: 192.168.211.132
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      # 请求路由
      routes:
        - id: changgou_goods_route  # 唯一标识符
#          uri: http://localhost:18081  # 指定要路由的服务
          uri: lb://goods  # 使用LoadBalancerClient实现负载均衡，后面goods是微服务的名称，主要应用于集群环境
          predicates:  # 路由断言（路由规则配置）
          # 所有以cloud.itheima.com:8001开头的请求，都被路由到http://localhost:18081
#            - Host=cloud.itheima.com**

          # 所有以/brand开始的请求，都被路由到http://localhost:18081
#            - Path=/brand/**

#            - Path=/**

            - Path=/api/goods/**

#            - Path=/api/brand/**
          filters:
          # 将请求路径中的第1个路径去掉，请求路径以'/'区分，一个'/'代表一个路径
            - StripPrefix=1

          # 用户请求/** -> /brand/**
#            - PrefixPath=/brand
          # 局部限流过滤器，默认使用redis的RateLimter算法（令牌桶算法）
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"  # 用户身份唯一识别标识符
                redis-rate-limiter.replenishRate: 1  # 每秒钟只允许有1个请求
                redis-rate-limiter.burstCapacity: 1  # 允许并发最多有1个请求（宽限的个数）

        - id: changgou_user_route
          uri: lb://user
          predicates:  # 路由断言（路由规则配置）
            - Path=/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**,/api/user/**
          filters:
            - StripPrefix=1

        - id: changgou_order_route
          uri: lb://order
          predicates:  # 路由断言（路由规则配置）
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true