server:
  port: 18090

spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  # RabbitMQ地址
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  appid: wx8397f8696b538317  # 微信公众账号或开放平台APP的唯一标识
  partner: 1473426802  # 财付通平台的商户账号
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb  # 财付通平台的商户密钥
  notifyurl: http://2h87186w76.wicp.vip:19304/weixin/pay/notify/url  # 回调地址（这里采用花生壳的内网穿透）

#位置支付交换机和队列（工作中要到MQ后台去创建，不然会报错）
mq:
  pay:
    exchange:
      order: exchange.order  # 发给哪个交换机
      seckillorder: exchange.seckillorder
    queue:
      order: queue.order  # 发给哪个队列
      seckillorder: queue.seckillorder
    routing:
      key: queue.order
      seckillkey: queue.seckillorder

